#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
bspc monitor -d 1 2 3

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config normal_border_color "#282828"
bspc config active_border_color "#d65d0e"
bspc config focused_border_color "#d65d0e"


setxkbmap -layout us,ru,ge -option 'grp:alt_shift_toggle'
nitrogen --restore &
dunst &
nm-applet &
volumeicon &
flameshot &
blueman-applet

