[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#1d211e"
blue = "#5073bf"
cyan = "#50bebe"
green = "#b9ca4a"
magenta = "#bd04fb"
red = "#f45f0c"
white = "#c8bda2"
yellow = "#c29059"

[colors.normal]
black = "#0f0e08"
blue = "#314277"
cyan = "#317777"
green = "#b5bd68"
magenta = "#8803b5"
red = "#b43003"
white = "#c8bda2"
yellow = "#ecac4a"

[colors.primary]
background = "#0f0e08"
foreground = "#f45f0c"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 9.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[window]
opacity = 1.0
