#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
bspc monitor -d 1 2 3 4 5  
xrandr -s 1920x1080
setxkbmap -layout us,ru,ge -option 'grp:alt_shift_toggle'
nitrogen --restore &
dunst &
killall nm-applet && nm-applet &
killall volumeicon && volumeicon &
flameshot &
blueman-applet


#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)


#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  5
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config click_to_focus                none
bspc config focus_follows_pointer         true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


#### BSPWM coloring ####
bspc config normal_border_color           "#0d0c0c"
bspc config active_border_color           "#938AA9"
bspc config focused_border_color          "#938AA9"
bspc config presel_feedback_color         "#938AA9"
bspc config urgent_border_color 	  "#e46876"



